# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Additive Part Design
email: prodj949@gmail.com
description: >
Additive Part Design is a 3D printing engineering design consulting service. We provide engineering
solutions geared towards one off replacement parts for legacy equipment or general solutions for
manufacturing environments. Every service provided is executed by the owner and operator. Need a
quick prototype printed? We got you. Need a parametric computer model of your part created? We got
you. Need a quick and dirty print with full GD&amp;T? We can do that too. If your solution can be completed in
plastic I am here to help.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://additivepartdesign.github.io" # the base hostname & protocol for your site
github_username:  AdditivePartDesign

# Build settings
markdown: kramdown
